name = "hoopshype-rumors-monitor"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"]

# Secrets (set via `wrangler secret put`):
# SLACK_WEBHOOK_URL

[[kv_namespaces]]
binding = "SEEN_RUMORS"
id = "b99f6a24157643eeb5d2a21c6cb932e8"